---
- hosts: all
  tasks:
  - name: Insert/update "multiline" in a file
    ansible.builtin.blockinfile:
      path: /home/dco/.ssh/authorized_keys
      marker: ""
      block: |
        ssh-rsa <LONG_KEY-STRINGS> user1@dco
        ssh-rsa <LONG_KEY-STRINGS> user2@dco
        ssh-rsa <LONG_KEY-STRINGS> user3@dco
