---
- hosts: all
  tasks:
  - name: Insert/update "multiline" in a file
    ansible.builtin.blockinfile:
      path: /home/dco/.ssh/authorized_keys
      marker: ""
      block: |
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCUsALkLvMGzW5/7P9+FPSRVGhOhQnuDJd7mx0n7vQIHZHGGfo6jVWtRUiWcOBkgUUOQU97cccsVDJWCWy9rk77ZK2JxBTXSx0UHTmg0PMUQMOteqQTLdBmk1N/TWO63lfR0ZUYd6MfJM2iH1KJTnD7kTaNDxjrsnVvqqyj3Go0L/FhDXgGg2grc9CbGSWfj7SqTkv0s17sypTEJTirmVq8pYEwO8kP8k0Z2iyYlb07r83x7g0kDQ/lvxYiemXB7KrY8mEh3LeeSv+rWRuhG4mvSuKWu1Ui4h0xg1Gw30mitihu1Mz9uMHWGDDmjK4wpVs6/jvq/iDb3JwPFUC0i39fhr38yzx73GZyAQpLowXH7AmHQ4CNAQXtHUY9heEAXD85i3F9UyY53G80HOdRRCgMRoa4WJJXxQOgL8+1jZLFdMGwI4r4wQAhB4h3KpckIr40+fYvoizeNW7Hl+HgZe9A9IkAZf0QWvb4q4C0uLs70/q2F9iNizAP0au/uz3C/zKnkh+p7aEhFUPhmklPDMNzt5OnRPthuRRSv6jAtzGw4PI2f9VON6FcpLFbQc6Fv06iqK3xTTAc1IAcpaevZX/8YTzAx2Js0TMcf3E4B1zVw8DfGJIEBUznJGcypmDpXiIpSziho6xrkCPIj+82SZ7PtIe+Iw+PHHOxFOXo5qZvOw== poniran@gmail.com
