---
- hosts: all
  tasks:
  - name: Insert/update "multiline" in a file
    ansible.builtin.blockinfile:
      path: /home/dco/.ssh/authorized_keys
      marker: ""
      block: |
        ssh-rsa <LONG_KEY-STRINGS> edwardnainggolan@dco
        ssh-rsa <LONG_KEY-STRINGS> benisantoso@dco
        ssh-rsa <LONG_KEY-STRINGS> poniranpo@dco
